<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-V5L8S5D" name="Secondary Email Verification Test(failed)" tests="1" failures="1" timestamp="18 Dec 2018 14:05:22 GMT" time="154.258" errors="0">
  <testcase name="testSecEmailVerification" time="149.22" classname="regression.SecondaryEmailVerificationTest">
    <failure type="java.lang.Exception" message="Failed to access verification">
      <![CDATA[java.lang.Exception: Failed to access verification
	at com.beanlogin.pages.MailinatorPage.getVerification(MailinatorPage.java:78)
	at regression.SecondaryEmailVerificationTest.testSecEmailVerification(SecondaryEmailVerificationTest.java:51)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testSecEmailVerification -->
</testsuite> <!-- Secondary Email Verification Test(failed) -->
